export const AVAILABLE_TOPICS = [
  "Global Economy",
  "Monetary Policy",
  "Equity Markets",
  "Fixed Income",
  "Commodities",
  "Emerging Markets",
  "Geopolitics",
  "Technology & AI",
  "Energy Transition",
  "Supply Chain",
  "Digital Assets",
  "Venture Capital",
  "M&A Activity",
  "ESG & Sustainability",
  "Real Estate",
  "Cybersecurity",
  "Healthcare & Biotech",
  "Consumer Trends",
  "Regulatory Shifts",
  "Central Bank Signals",
  "Quantum Computing",
  "Space Economy",
  "Semiconductor Industry",
  "Defense Technology",
  "Global Trade Policy",
  "Demographic Shifts",
  "Infrastructure Development",
  "Fintech Innovation",
  "Agri-Tech",
  "Circular Economy"
];
